baseURL = "/"
languageCode = "en-nz"
title = "Coder Frontline"
theme = "hermit"
enableRobotsTXT = true
copyright = "Creative Commons Attribution 4.0 International License"
googleAnalytics = "UA-74441668-1"
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
  name = "Shawn Lam"

[taxonomies]
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
 
  # themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Musings from a coder on the frontline"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # gitUrl = "https://github.com/Someone/SomeRepo/commit/" # Prefix of link to the git commit detail page. GitInfo must be enabled.
  justifyContent = false  # Set "text-align: justify" to .content, requires extended version of Hugo
  # bgImg = ""  #  Homepage background-image URL

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/shawnlamnz"

  [[params.social]]
    name = "github"
    url = "https://github.com/zemien"
    
[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
    
  [permalinks]
  posts = "/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true